### ISSUE TITLE
Where is the energy based model?

### ISSUE THREAD

**Issue by amrhamedp** [MinkaiXu/CGCF-ConfGen#2]
Hello @luost26 
Where is the ebm based on schnett in the code?
I am not sure if I was able to identify where it is...I just looked quickly

**Comment by luost26** [comment]
Hi,

Since we have another work about the energy-based model under review at some conference, we cannot release that part of code for now. I am sorry about that. It is expected to be released in some other repository in the following months.
You may only test CGCF. It is ok because CGCF itself is the major contributor to the performance gain.

Thanks
